spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate.hibernate.format_sql: true


  datasource:
    username: "dbuser"
    password: "12345"
    url: jdbc:postgresql://db-cart:5432/cart
    driver-class-name: "org.postgresql.Driver"

  sql:
    init:
      mode: always

server:
  port: 0