spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate.hibernate.format_sql: true


  datasource:
    username: "dbuser"
    password: "12345"
    url: jdbc:postgresql://localhost:5435/warehouse
    driver-class-name: "org.postgresql.Driver"

  sql:
    init:
      mode: always

server:
  port: 0

warehouse:
  address:
    country: "Russia"
    city: "Moscow"
    street: "Arbat"
    house: "14"
    flat: "1"